{{- if and (index .Values "docker-registry" "enabled") (not .Values.istio.enabled) }}
apiVersion: {{ .Values.ingress.apiVersion | default "networking.k8s.io/v1" }}
kind: Ingress
metadata:
  annotations:
  {{- template "ingressAnnotations" . }}
  name: docker-registry
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: jenkins-x-docker-registry
            port: 5000
{{- if eq "NodePort" .Values.jxRequirements.ingress.serviceType }}
        path: "/docker-registry"
{{- else if .Values.ingress.customHosts.dockerRegistry }}
        path: "/"
    host: {{ .Values.ingress.customHosts.dockerRegistry }}
{{- else if .Values.jxRequirements.ingress.domain }}
        path: "/"
    host: {{ .Values.ingress.prefix.dockerRegistry }}{{ .Values.jxRequirements.ingress.namespaceSubDomain }}{{ .Values.jxRequirements.ingress.domain }}
{{- end }}
{{- if .Values.jxRequirements.ingress.tls.enabled }}
  tls:
  - hosts:
  {{- if .Values.ingress.customHosts.dockerRegistry }}
    - {{ .Values.ingress.customHosts.dockerRegistry }}
  {{- else }}
    - {{ .Values.ingress.prefix.dockerRegistry }}{{ .Values.jxRequirements.ingress.namespaceSubDomain }}{{ .Values.jxRequirements.ingress.domain }}
  {{- end }}
{{- if index .Values "docker-registry" "ingress" "tls" "secretName" }}
    secretName: "{{ index .Values "docker-registry" "ingress" "tls" "secretName" }}"
{{- else if .Values.jxRequirements.ingress.tls.secretName }}
    secretName: "{{ .Values.jxRequirements.ingress.tls.secretName }}"
{{- else if .Values.jxRequirements.ingress.tls.production }}
    secretName: "tls-{{ .Values.jxRequirements.ingress.domain | replace "." "-" }}-p"
{{- else }}
    secretName: "tls-{{ .Values.jxRequirements.ingress.domain | replace "." "-" }}-s"
{{- end }}
{{- end }}
{{- end }}
