apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gcpods-cluster-scoped-ns-listing
rules:
  # Only have to list namespaces to find those labelled namespaces, where pods should be deleted
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
