---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gcactivities-cluster-scoped
rules:
  - apiGroups:
      - jenkins.io
    resources:
      - pipelineactivities
    verbs:
      - list
      - delete
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
    verbs:
      - get
      - list
      - watch
      - delete
  - apiGroups:
    - lighthouse.jenkins.io
    resources:
      - lighthousejobs
    verbs:
      - list
      - delete
