apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gcjobs
  namespace: {{ .Values.gcbootjobs.role.ns | default "jx-git-operator" | quote }}
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - delete
      - list
