apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gcpods-per-namespace
rules:
  - apiGroups:
      - jenkins.io
    resources:
      - environments
      - plugins
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - delete
      - list
