apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gcjobs
  namespace: {{ .Values.gc.jobs.rb.ns | default "jx-git-operator" | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gcjobs
subjects:
  - kind: ServiceAccount
    name: jx-gcjobs
    namespace: {{ .Values.gc.jobs.rb.ns | default "jx-git-operator" | quote }}
